"""
Layers 3-4: LLM Generation via Claude CLI
Assembles prompts from templates + data, calls `claude -p` via subprocess.
"""

import json
import os
import subprocess
import sys
import time
from pathlib import Path


PIPELINE_DIR = Path(__file__).parent
PROMPTS_DIR = PIPELINE_DIR / "prompts"
OUTPUT_DIR = PIPELINE_DIR.parent / "output"


def read_file(path):
    """Read a file and return its contents."""
    with open(path) as f:
        return f.read()


def read_json(path):
    """Read a JSON file and return pretty-printed string."""
    with open(path) as f:
        data = json.load(f)
    return json.dumps(data, indent=2, default=str)


def call_claude(prompt, model="sonnet", slug="", layer=""):
    """
    Call claude CLI in non-interactive print mode.
    Saves the prompt to a file for debugging/manual runs.
    Returns the model's response text.
    """
    # Always save the prompt so it can be inspected or run manually
    out_dir = OUTPUT_DIR / slug if slug else Path("/tmp")
    out_dir.mkdir(parents=True, exist_ok=True)
    prompt_file = out_dir / f"_prompt_layer{layer}.md"
    with open(prompt_file, "w") as f:
        f.write(prompt)
    print(f"    Prompt saved to: {prompt_file}")
    print(f"    Prompt size: {len(prompt):,} chars")
    print(f"    Calling claude -p --model {model} ...")
    print(f"    (To run manually: cat '{prompt_file}' | claude -p --model {model})")

    start = time.time()
    result = subprocess.run(
        ["claude", "-p", "--model", model],
        input=prompt,
        capture_output=True,
        text=True,
        timeout=1200,  # 20 min timeout
    )
    elapsed = time.time() - start

    if result.returncode != 0:
        print(f"    ERROR: claude exited with code {result.returncode} ({elapsed:.1f}s)")
        print(f"    stderr ({len(result.stderr)} chars): {result.stderr or '(empty)'}")
        print(f"    stdout ({len(result.stdout)} chars): {result.stdout or '(empty)'}")
        print(f"    ANTHROPIC_API_KEY set: {bool(os.environ.get('ANTHROPIC_API_KEY'))}")
        sys.exit(1)

    output_chars = len(result.stdout)
    print(f"    Done in {elapsed:.1f}s ({output_chars:,} chars output)")
    return result.stdout, elapsed


def generate_style_profile(slug):
    """
    Layer 3: Assemble prompt from templates + aggregated data, call Claude,
    write style_profile.md.
    """
    out_dir = OUTPUT_DIR / slug
    agg_dir = out_dir / "aggregated"
    raw_dir = out_dir / "raw"

    print("\n[Layer 3] Generating style profile...")

    # Read prompt templates
    templates = [
        PROMPTS_DIR / "layer3_profile_assembly" / "style_dna_synthesis.md",
        PROMPTS_DIR / "layer3_profile_assembly" / "constraint_assembly.md",
    ]
    prompt_instructions = "\n\n---\n\n".join(read_file(t) for t in templates)

    # Read data files
    data_files = {
        "customer_profile": raw_dir / "customer_profile.json",
        "order_summary": raw_dir / "order_summary.json",
        "brand_affinities": agg_dir / "brand_affinities.json",
        "category_affinities": agg_dir / "category_affinities.json",
        "color_profile": agg_dir / "color_profile.json",
        "dod_selectivity": agg_dir / "dod_selectivity.json",
        "dod_affinities": agg_dir / "dod_affinities.json",
        "satisfaction_trajectory": agg_dir / "satisfaction_trajectory.json",
        "exclusion_list": agg_dir / "exclusion_list.json",
        "qualitative_signals": agg_dir / "qualitative_signals.json",
    }

    data_sections = []
    for name, path in data_files.items():
        if path.exists():
            data_sections.append(f"### {name}\n```json\n{read_json(path)}\n```")
        else:
            data_sections.append(f"### {name}\n*No data available*")

    data_block = "\n\n".join(data_sections)

    # Assemble full prompt
    prompt = f"""You are generating a style profile for a ThreadBeast customer.

## Instructions

Follow these prompt templates exactly:

{prompt_instructions}

## Customer Data

{data_block}

## Task

Using the instructions and data above, generate a complete style profile in markdown format.
Output ONLY the markdown content — no preamble, no commentary."""

    response, elapsed = call_claude(prompt, model="sonnet", slug=slug, layer="3")

    # Write output with timing metadata
    output_path = out_dir / "style_profile.md"
    with open(output_path, "w") as f:
        f.write(response)
        f.write(f"\n\n---\n*Generated by RECSYS MVP Pipeline · Layer 3 (sonnet) · "
                f"{elapsed:.1f}s · {len(prompt):,} chars prompt · "
                f"{len(response):,} chars output*\n")

    print(f"    Saved to: {output_path}")
    return output_path


def generate_outfit_recommendations(slug):
    """
    Layer 4: Assemble prompt from templates + style profile + candidates,
    call Claude, write outfit_recommendations.md.
    """
    out_dir = OUTPUT_DIR / slug
    agg_dir = out_dir / "aggregated"

    print("\n[Layer 4] Generating outfit recommendations...")

    # Read prompt templates
    templates = [
        PROMPTS_DIR / "layer4_outfit_construction" / "outfit_builder.md",
        PROMPTS_DIR / "layer4_outfit_construction" / "anti_recommendations.md",
    ]
    prompt_instructions = "\n\n---\n\n".join(read_file(t) for t in templates)

    # Read the style profile just generated
    style_profile_path = out_dir / "style_profile.md"
    if not style_profile_path.exists():
        print("    ERROR: style_profile.md not found. Run Layer 3 first.")
        sys.exit(1)
    style_profile = read_file(style_profile_path)

    # Read candidate inventory and exclusion list
    candidate_inv = agg_dir / "candidate_inventory.json"
    exclusion_list = agg_dir / "exclusion_list.json"

    candidates_block = ""
    if candidate_inv.exists():
        candidates_block = f"### candidate_inventory\n```json\n{read_json(candidate_inv)}\n```"
    else:
        candidates_block = "### candidate_inventory\n*No inventory data available*"

    exclusions_block = ""
    if exclusion_list.exists():
        exclusions_block = f"### exclusion_list\n```json\n{read_json(exclusion_list)}\n```"

    # Assemble full prompt
    prompt = f"""You are building outfit recommendations for a ThreadBeast customer.

## Instructions

Follow these prompt templates exactly:

{prompt_instructions}

## Customer Style Profile

{style_profile}

## Available Inventory (pre-filtered to customer sizes, opted-out items removed)

{candidates_block}

## Recently Sent Items (hard exclusions — never recommend these barcodes)

{exclusions_block}

## Task

Using the style profile, available inventory, and exclusion list above, generate:
1. 5-7 complete outfit recommendations with rationalization chains
2. Anti-recommendations section

Output ONLY the markdown content — no preamble, no commentary."""

    response, elapsed = call_claude(prompt, model="opus", slug=slug, layer="4")

    # Write output with timing metadata
    output_path = out_dir / "outfit_recommendations.md"
    with open(output_path, "w") as f:
        f.write(response)
        f.write(f"\n\n---\n*Generated by RECSYS MVP Pipeline · Layer 4 (opus) · "
                f"{elapsed:.1f}s · {len(prompt):,} chars prompt · "
                f"{len(response):,} chars output*\n")

    print(f"    Saved to: {output_path}")
    return output_path


def main():
    if len(sys.argv) < 2:
        print("Usage: python generate.py <customer_slug> [layer]")
        print("  layer: 3, 4, or all (default: all)")
        sys.exit(1)

    slug = sys.argv[1]
    layer = sys.argv[2] if len(sys.argv) > 2 else "all"

    if not (OUTPUT_DIR / slug / "aggregated").exists():
        print(f"ERROR: No aggregated data found for '{slug}'")
        print(f"  Run: python run_customer.py <email> first")
        sys.exit(1)

    if layer in ("3", "all"):
        generate_style_profile(slug)
    if layer in ("4", "all"):
        generate_outfit_recommendations(slug)


if __name__ == "__main__":
    main()
